# Generated by Django 5.2.4 on 2025-07-25 00:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transport', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('pickup_location', models.CharField(max_length=100)),
                ('dropoff_location', models.CharField(max_length=100)),
                ('insurance_provider', models.CharField(max_length=100)),
                ('medical_necessity', models.CharField(max_length=100)),
                ('justification', models.TextField(blank=True, null=True)),
                ('vendor_selected', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='transport.transportvendor')),
            ],
        ),
    ]
